// <auto-generated />
namespace TagManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TagManager_Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagManager_Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121801141_TagManager_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
